In [1]:
import numpy as np

In [2]:
l1 = [1,2,3,4,5,6,7,8,9,10]
l2= []
for i in range(1, 11):
    l2.append(i**2)
    
print(l2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


# 1 dimentional array

In [16]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a
name = "gurupreeth"

In [4]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a = np.array(l1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(a.ndim)

1


In [7]:
a.ndim

1

In [8]:
a.shape

(10,)

In [9]:
len(a)

10

# 2 dimentional array:-

In [10]:
a = np.array([[1,1],[2,2]])
a

array([[1, 1],
       [2, 2]])

In [11]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a.ndim

2

In [13]:
a.shape

(2, 3)

In [14]:
len(a)

2

In [15]:
for i in range(1,3):
    for j in range(1,4):
        print(i,end="")
    print()

111
222


In [18]:
a = np.array( [  [[1,2],[3,4]],  [[5,6],[7,8]] ] )
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
print(name)

gurupreeth


In [20]:
a.ndim

3

In [21]:
a.shape

(2, 2, 2)

In [26]:
a = np.array( [  [[1,2],[3,4]],  [[5,6],[7,8]] , [[9,10],[11,12]]  ] )
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [27]:
a.shape

(3, 2, 2)

In [28]:
a = np.array( [  [[1,2],[3,4]],  [[5,6],[7,8]] , [[9,10],[11,12]]   , [[19,20],[21,22]]  ] )
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[19 20]
  [21 22]]]


In [29]:
a.shape

(4, 2, 2)

# inbuilt numpy functions:- 

In [30]:
a = np.linspace(0,1,10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
1.0 - .88888889

0.11111110999999996

In [32]:
0.88888889 - 0.77777778

0.11111111000000007

In [33]:
a = np.linspace(0,1,5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
a = np.linspace(0,100,4)
a

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [40]:
a = np.linspace(1,100,200)
a

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

In [41]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
a = np.diag([10,20,30,40])
print(a)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [45]:
a.dtype

dtype('int32')

In [46]:
a = np.eye(5)
a.dtype

dtype('float64')

In [50]:
a = np.array([1,2,3,4,5,6], dtype="int64")
a


array([1, 2, 3, 4, 5, 6], dtype=int64)

In [48]:
a.dtype

dtype('float64')

In [51]:
a = np.array([1,2,3,4,5,6], dtype="float64")
a

array([1., 2., 3., 4., 5., 6.])

In [52]:
a = np.array([2+3j, 5+4j])
print(a)

[2.+3.j 5.+4.j]


In [53]:
a.dtype

dtype('complex128')

In [54]:
a = np.array(["rashmi", "umais", "satish"])
print(a)

['rashmi' 'umais' 'satish']


In [55]:
a.dtype

dtype('<U6')