In [5]:
import numpy as np

In [2]:
l1 = [1,2,3,4,5,6,7,8,9,10]
l2 = []
for i in range(1,11):
    l2.append(i**2)
print(l2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


# 1 Dimentional Array:

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a = np.array(l1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
a.ndim

1

In [9]:
print(a.ndim)

1


In [10]:
a.shape

(10,)

In [11]:
len(a)

10

# 2 Dimentional Array:

In [13]:
a = np.array([[1,1],[2,2]])
a

array([[1, 1],
       [2, 2]])

In [15]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a.ndim

2

In [17]:
a.shape

(2, 3)

In [18]:
len(a)

2

In [19]:
for i in range(1,3):
    for j in range(1,4):
        print(i,end="")
    print()
    

111
222


In [21]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
a.ndim

3

In [23]:
a.shape

(2, 2, 2)

In [25]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [26]:
a.shape

(3, 2, 2)

In [27]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]],[[13,14],[15,16]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [28]:
a.shape

(4, 2, 2)

# Inbuilt numpy functions:

In [29]:
a = np.linspace(0,1,10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [30]:
a = np.linspace(0,1,5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
a = np.linspace(0,100,4)
a

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [33]:
a = np.linspace(1,100,100)
a

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [34]:
a = np.linspace(0,100,200)
a

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

In [35]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
a = np.eye(5) #identity matrix
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
a = np.diag([10,20,30,40]) #Diagonal Matrix
a

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [39]:
a.dtype

dtype('int32')

In [42]:
a = np.eye(5) #identity matrix
a.dtype

dtype('float64')

In [43]:
a = np.array([1,2,3,4,5,6,7], dtype="int64")
a

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [44]:
a = np.array([1,2,3,4,5,6,7], dtype="float64")
a

array([1., 2., 3., 4., 5., 6., 7.])

In [46]:
a = np.array([2+3j, 5+4j])
print(a)

[2.+3.j 5.+4.j]


In [47]:
a.dtype

dtype('complex128')

In [52]:
a = np.array(["Rashmi","Umais","Satish"])
print(a)

['Rashmi' 'Umais' 'Satish']


In [53]:
a.dtype

dtype('<U6')

# Indexing and slicing:

In [8]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a = np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [18]:
a[1,1]

2

In [19]:
a[1,1] = 200
a

array([[  1,   0,   0],
       [  0, 200,   0],
       [  0,   0,   3]])

In [20]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a = np.arange(1,10)
print(a[::2])

[1 3 5 7 9]


In [29]:
a = np.arange(1,10)
print(a[5:])

[6 7 8 9]


In [34]:
a = np.arange(1,10)
a[5:]=100
a

array([  1,   2,   3,   4,   5, 100, 100, 100, 100])

In [41]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([0,1,2,3,4])


In [42]:
b[::-1]

array([4, 3, 2, 1, 0])

In [43]:
a[5:] = b[::-1]

In [44]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [45]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

# Mask:

In [51]:
mask = (a%2==0)
a = np.random.randint(0,100,15)
a

array([89, 96, 67, 49, 80, 55, 60, 36, 40, 29, 25, 60, 87, 96, 71])

In [52]:
alleven = a[mask]
print(alleven)

[96 67 55 40 87 71]


In [53]:
a[mask] = 0
a

array([89,  0,  0, 49, 80,  0, 60, 36,  0, 29, 25, 60,  0, 96,  0])

# Advanced Indexing:

In [57]:
a = np.arange(100)
print(a[::10])

[ 0 10 20 30 40 50 60 70 80 90]


In [58]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
a[[2,3,2,4,5]]

array([20, 30, 20, 40, 50])

# Basic arathimetic operations on Numpy arrays:

In [62]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
a+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [65]:
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [66]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [67]:
a**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [68]:
a**5

array([     1,     32,    243,   1024,   3125,   7776,  16807,  32768,
        59049, 100000], dtype=int32)

In [70]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [71]:
a*a

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [73]:
a.dot(a)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [74]:
a = np.array([1,2,3,4])
b = np.array([5,2,4,4])
a==b

array([False,  True, False,  True])

In [75]:
a<b

array([ True, False,  True, False])

In [76]:
a>b

array([False, False, False, False])

In [77]:
a>=b

array([False,  True, False,  True])

In [78]:
a<=b

array([ True,  True,  True,  True])

In [81]:
a = np.array([1,2,3,4])
b = np.array([5,2,4])
a==b

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until


False

In [84]:
a = np.array([1,1,0,0])
b = np.array([1,0,1,1])
np.logical_and(a,b)

array([ True, False, False, False])

In [85]:
a = np.array([1,1,0,0])
b = np.array([1,0,1,0])
np.logical_or(a,b)

array([ True,  True,  True, False])

In [98]:
a = np.arange(4)
b = np.arange(0,2)


In [88]:
np.sum(a)

6

In [89]:
a = np.array([[1,1],[2,2]])
a

array([[1, 1],
       [2, 2]])

In [91]:
np.sum(a,axis = 0)

array([3, 3])

In [92]:
np.sum(a,axis = 1)

array([2, 4])

In [93]:
np.all([True,False,True])

False

In [94]:
np.all([True,False,True])

True

In [95]:
np.all([False,False,False])

False

In [96]:
np.all([True,True,True])

True

In [97]:
np.any([True,False,True])

True